### ISSUE TITLE
WARNING: Will not .Save to XXX\Docs\Convert-CommandsToList.md, because that path will not be readable on all operating systems.

### ISSUE THREAD

**Issue by PrzemyslawKlys** [StartAutomating/HelpOut#175]
![image](https://github.com/StartAutomating/HelpOut/assets/15063294/f4d7dab5-4940-4bbf-afdf-130c6c665b0b)

The path exists, so I am not sure what problem do we have here :)

**Comment by shaun-lawrie-ptml** [comment]
The fix for https://github.com/StartAutomating/HelpOut/issues/163 breaks generating markdown help on windows because the drive has a colon in it.

![image](https://github.com/StartAutomating/HelpOut/assets/43252622/77dde016-11e8-48e6-a41c-6f236c332f39)
I believe it should omit the qualifier when checking the file name is legit:
```pwsh
Split-Path "C:\Dev\test.txt" -NoQualifier
> \Dev\test.txt
```
