### ISSUE TITLE
HelpOut is broken and publishing mess

### ISSUE THREAD

**Issue by PrzemyslawKlys** [StartAutomating/HelpOut#177]
Newest version breaks the module:

![image](https://github.com/StartAutomating/HelpOut/assets/15063294/6067077e-06e4-4e34-bcf3-385a3f6d30b0)

![image](https://github.com/StartAutomating/HelpOut/assets/15063294/75adc0aa-725f-470d-bc71-686fad2f80c9)

And PSGallery is a mess :)

![image](https://github.com/StartAutomating/HelpOut/assets/15063294/8289b536-e5a9-415e-9409-e818734bacb5)

**Comment by StartAutomating** [comment]
@PrzemyslawKlys works on my machine

File list also looks normal.

![image](https://github.com/StartAutomating/HelpOut/assets/1043665/c07881f9-6df4-48f8-948b-6147416d6a09)

Rechecked @ShaunLawrie's recent PR, and it does not seem likely to have caused this (nor am I getting a reliable repro)

@ShaunLawrie could you check on your machine when you get the chance?
@PrzemyslawKlys can you dig a bit deeper as to why this might be?  The .psd1 doesn't restrict its exports, so this should work.

**Comment by StartAutomating** [comment]
Closing as issue could not be reproduced.

**Comment by ShaunLawrie** [comment]
I think this happens if you haven't run import-module
![image](https://github.com/StartAutomating/HelpOut/assets/13159458/422ea43c-363d-4ed0-9f96-38de732f01d3)

You ran get-module and it returned nothing which usually indicates it's not loaded, not that it doesn't exist. Once you import the module it should return a value 🤞🏻
